const FileManager = require('../../helpers/fileManager');


class Prueba{
    async pruebilla(){
        const monthsConf = await FileManager.getConfigJsonFile("./src/config/highOfucate.json");
        console.log(monthsConf);
    }

    otraPrueba(){
        const variable1 = {
            compact: true,
            controlFlowFlattening: true,
            controlFlowFlatteningThreshold: 1,
            deadCodeInjection: true,
            deadCodeInjectionThreshold: 1,
            debugProtection: true,
            debugProtectionInterval: true,
            disableConsoleOutput: true,
            log: false,
            mangle: false,
            renameGlobals: false,
            rotateStringArray: true,
            selfDefending: true,
            stringArray: true,
            stringArrayEncoding: 'rc4',
            stringArrayThreshold: 1,
            unicodeEscapeSequence: false,
            estasEsUnaMasDeLasVariablesVar01: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar02: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 2",
            estasEsUnaMasDeLasVariablesVar03: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 3",
            estasEsUnaMasDeLasVariablesVar04: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar05: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar06: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar07: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar08: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar09: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar10: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar11: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar12: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar13: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar14: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar15: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar16: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar17: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar18: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar19: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar20: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar21: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar22: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar23: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar24: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar25: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar26: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar27: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar28: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar29: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar30: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1"

        };
        console.log(variable1); 
    }

    otraPrueba1(){
        const variable1 = {
            compact: true,
            controlFlowFlattening: true,
            controlFlowFlatteningThreshold: 1,
            deadCodeInjection: true,
            deadCodeInjectionThreshold: 1,
            debugProtection: true,
            debugProtectionInterval: true,
            disableConsoleOutput: true,
            log: false,
            mangle: false,
            renameGlobals: false,
            rotateStringArray: true,
            selfDefending: true,
            stringArray: true,
            stringArrayEncoding: 'rc4',
            stringArrayThreshold: 1,
            unicodeEscapeSequence: false,
            estasEsUnaMasDeLasVariablesVar01: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar02: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 2",
            estasEsUnaMasDeLasVariablesVar03: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 3",
            estasEsUnaMasDeLasVariablesVar04: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar05: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar06: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar07: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar08: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar09: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar10: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar11: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar12: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar13: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar14: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar15: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar16: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar17: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar18: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar19: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar20: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar21: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar22: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar23: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar24: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar25: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar26: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar27: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar28: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar29: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar30: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1"

        };
        console.log(variable1); 
    }
   
    otraPrueba2(){
        const variable1 = {
            compact: true,
            controlFlowFlattening: true,
            controlFlowFlatteningThreshold: 1,
            deadCodeInjection: true,
            deadCodeInjectionThreshold: 1,
            debugProtection: true,
            debugProtectionInterval: true,
            disableConsoleOutput: true,
            log: false,
            mangle: false,
            renameGlobals: false,
            rotateStringArray: true,
            selfDefending: true,
            stringArray: true,
            stringArrayEncoding: 'rc4',
            stringArrayThreshold: 1,
            unicodeEscapeSequence: false,
            estasEsUnaMasDeLasVariablesVar01: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar02: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 2",
            estasEsUnaMasDeLasVariablesVar03: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 3",
            estasEsUnaMasDeLasVariablesVar04: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar05: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar06: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar07: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar08: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar09: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar10: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar11: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar12: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar13: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar14: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar15: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar16: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar17: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar18: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar19: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar20: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar21: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar22: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar23: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar24: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar25: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar26: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar27: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar28: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar29: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar30: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1"

        };
        console.log(variable1); 
    }

    otraPrueba3(){
        const variable1 = {
            compact: true,
            controlFlowFlattening: true,
            controlFlowFlatteningThreshold: 1,
            deadCodeInjection: true,
            deadCodeInjectionThreshold: 1,
            debugProtection: true,
            debugProtectionInterval: true,
            disableConsoleOutput: true,
            log: false,
            mangle: false,
            renameGlobals: false,
            rotateStringArray: true,
            selfDefending: true,
            stringArray: true,
            stringArrayEncoding: 'rc4',
            stringArrayThreshold: 1,
            unicodeEscapeSequence: false,
            estasEsUnaMasDeLasVariablesVar01: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar02: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 2",
            estasEsUnaMasDeLasVariablesVar03: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 3",
            estasEsUnaMasDeLasVariablesVar04: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar05: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar06: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar07: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar08: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar09: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar10: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar11: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar12: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar13: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar14: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar15: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar16: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar17: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar18: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar19: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar20: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar21: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar22: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar23: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar24: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar25: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar26: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar27: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar28: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar29: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar30: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1"

        };
        console.log(variable1); 
    }

    otraPrueba4(){
        const variable1 = {
            compact: true,
            controlFlowFlattening: true,
            controlFlowFlatteningThreshold: 1,
            deadCodeInjection: true,
            deadCodeInjectionThreshold: 1,
            debugProtection: true,
            debugProtectionInterval: true,
            disableConsoleOutput: true,
            log: false,
            mangle: false,
            renameGlobals: false,
            rotateStringArray: true,
            selfDefending: true,
            stringArray: true,
            stringArrayEncoding: 'rc4',
            stringArrayThreshold: 1,
            unicodeEscapeSequence: false,
            estasEsUnaMasDeLasVariablesVar01: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar02: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 2",
            estasEsUnaMasDeLasVariablesVar03: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 3",
            estasEsUnaMasDeLasVariablesVar04: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar05: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar06: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar07: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar08: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar09: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar10: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar11: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar12: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar13: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar14: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar15: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar16: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar17: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar18: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar19: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar20: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar21: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar22: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar23: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar24: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar25: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar26: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar27: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar28: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar29: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar30: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1"

        };
        console.log(variable1); 
    }

    otraPrueba5(){
        const variable1 = {
            compact: true,
            controlFlowFlattening: true,
            controlFlowFlatteningThreshold: 1,
            deadCodeInjection: true,
            deadCodeInjectionThreshold: 1,
            debugProtection: true,
            debugProtectionInterval: true,
            disableConsoleOutput: true,
            log: false,
            mangle: false,
            renameGlobals: false,
            rotateStringArray: true,
            selfDefending: true,
            stringArray: true,
            stringArrayEncoding: 'rc4',
            stringArrayThreshold: 1,
            unicodeEscapeSequence: false,
            estasEsUnaMasDeLasVariablesVar01: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar02: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 2",
            estasEsUnaMasDeLasVariablesVar03: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 3",
            estasEsUnaMasDeLasVariablesVar04: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar05: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar06: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar07: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar08: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar09: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar10: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar11: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar12: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar13: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar14: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar15: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar16: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar17: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar18: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar19: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar20: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar21: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar22: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar23: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar24: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar25: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar26: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar27: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar28: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar29: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar30: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1"

        };
        console.log(variable1); 
    }


    otraPrueba6(){
        const variable1 = {
            compact: true,
            controlFlowFlattening: true,
            controlFlowFlatteningThreshold: 1,
            deadCodeInjection: true,
            deadCodeInjectionThreshold: 1,
            debugProtection: true,
            debugProtectionInterval: true,
            disableConsoleOutput: true,
            log: false,
            mangle: false,
            renameGlobals: false,
            rotateStringArray: true,
            selfDefending: true,
            stringArray: true,
            stringArrayEncoding: 'rc4',
            stringArrayThreshold: 1,
            unicodeEscapeSequence: false,
            estasEsUnaMasDeLasVariablesVar01: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar02: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 2",
            estasEsUnaMasDeLasVariablesVar03: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 3",
            estasEsUnaMasDeLasVariablesVar04: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar05: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar06: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar07: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar08: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar09: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar10: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar11: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar12: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar13: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar14: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar15: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar16: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar17: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar18: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar19: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar20: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar21: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar22: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar23: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar24: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar25: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar26: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar27: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar28: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar29: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar30: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1"

        };
        console.log(variable1); 
    }

    otraPrueba7(){
        const variable1 = {
            compact: true,
            controlFlowFlattening: true,
            controlFlowFlatteningThreshold: 1,
            deadCodeInjection: true,
            deadCodeInjectionThreshold: 1,
            debugProtection: true,
            debugProtectionInterval: true,
            disableConsoleOutput: true,
            log: false,
            mangle: false,
            renameGlobals: false,
            rotateStringArray: true,
            selfDefending: true,
            stringArray: true,
            stringArrayEncoding: 'rc4',
            stringArrayThreshold: 1,
            unicodeEscapeSequence: false,
            estasEsUnaMasDeLasVariablesVar01: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar02: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 2",
            estasEsUnaMasDeLasVariablesVar03: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 3",
            estasEsUnaMasDeLasVariablesVar04: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar05: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar06: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar07: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar08: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar09: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar10: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar11: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar12: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar13: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar14: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar15: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar16: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar17: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar18: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar19: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar20: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar21: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar22: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar23: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar24: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar25: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar26: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar27: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar28: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar29: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar30: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1"

        };
        console.log(variable1); 
    }

    otraPrueba8(){
        const variable1 = {
            compact: true,
            controlFlowFlattening: true,
            controlFlowFlatteningThreshold: 1,
            deadCodeInjection: true,
            deadCodeInjectionThreshold: 1,
            debugProtection: true,
            debugProtectionInterval: true,
            disableConsoleOutput: true,
            log: false,
            mangle: false,
            renameGlobals: false,
            rotateStringArray: true,
            selfDefending: true,
            stringArray: true,
            stringArrayEncoding: 'rc4',
            stringArrayThreshold: 1,
            unicodeEscapeSequence: false,
            estasEsUnaMasDeLasVariablesVar01: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar02: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 2",
            estasEsUnaMasDeLasVariablesVar03: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 3",
            estasEsUnaMasDeLasVariablesVar04: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar05: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar06: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar07: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar08: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar09: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar10: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar11: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar12: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar13: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar14: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar15: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar16: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar17: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar18: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar19: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar20: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar21: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar22: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar23: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar24: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar25: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar26: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar27: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar28: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar29: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar30: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1"

        };
        console.log(variable1); 
    }

    otraPrueba9(){
        const variable1 = {
            compact: true,
            controlFlowFlattening: true,
            controlFlowFlatteningThreshold: 1,
            deadCodeInjection: true,
            deadCodeInjectionThreshold: 1,
            debugProtection: true,
            debugProtectionInterval: true,
            disableConsoleOutput: true,
            log: false,
            mangle: false,
            renameGlobals: false,
            rotateStringArray: true,
            selfDefending: true,
            stringArray: true,
            stringArrayEncoding: 'rc4',
            stringArrayThreshold: 1,
            unicodeEscapeSequence: false,
            estasEsUnaMasDeLasVariablesVar01: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar02: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 2",
            estasEsUnaMasDeLasVariablesVar03: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 3",
            estasEsUnaMasDeLasVariablesVar04: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar05: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar06: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar07: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar08: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar09: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar10: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar11: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar12: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar13: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar14: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar15: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar16: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar17: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar18: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar19: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar20: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar21: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar22: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar23: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar24: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar25: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar26: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar27: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar28: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar29: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar30: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1"

        };
        console.log(variable1); 
    }    


    otraPrueba10(){
        const variable1 = {
            compact: true,
            controlFlowFlattening: true,
            controlFlowFlatteningThreshold: 1,
            deadCodeInjection: true,
            deadCodeInjectionThreshold: 1,
            debugProtection: true,
            debugProtectionInterval: true,
            disableConsoleOutput: true,
            log: false,
            mangle: false,
            renameGlobals: false,
            rotateStringArray: true,
            selfDefending: true,
            stringArray: true,
            stringArrayEncoding: 'rc4',
            stringArrayThreshold: 1,
            unicodeEscapeSequence: false,
            estasEsUnaMasDeLasVariablesVar01: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar02: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 2",
            estasEsUnaMasDeLasVariablesVar03: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 3",
            estasEsUnaMasDeLasVariablesVar04: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar05: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar06: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar07: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar08: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar09: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar10: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar11: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar12: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar13: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar14: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar15: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar16: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar17: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar18: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar19: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar20: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar21: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar22: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar23: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar24: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar25: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar26: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar27: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar28: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar29: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1",
            estasEsUnaMasDeLasVariablesVar30: "Esta es toda una leyenda para aumentar el tamaño del javascript,esperamos que esto pueda funcionar 1"

        };
        console.log(variable1); 
    }

}    


module.exports = Prueba;